version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:28017/nest
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - '28017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
